version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: preferred_deals_api_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rails API Backend (using existing Dockerfile)
  backend:
    build:
      context: ./preferred_deals_api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/preferred_deals_api_production
      RAILS_ENV: production
      SECRET_KEY_BASE: your_secret_key_base_here
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    command: >
      sh -c "
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails server -b 0.0.0.0 -p 3001
      "

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

volumes:
  postgres_data:
