# Railway configuration for React frontend
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildArgs = ["REACT_APP_API_URL"]

[deploy]
startCommand = "/docker-entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
# REACT_APP_API_URL should be set in Railway dashboard
# Example: REACT_APP_API_URL = "https://your-backend.railway.app/api/v1"
