# Railway configuration for React frontend
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c \"sed -i s/listen\\ 80\\;/listen\\ $PORT\\;/g /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
