# Railway configuration for React frontend
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c \"sed -i 's/listen 80;/listen $PORT;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
# Note: Set REACT_APP_API_URL to your backend URL after deployment
# Example: REACT_APP_API_URL = "https://your-backend.railway.app"
